version: '3.7'

# Services/Containers to orchestrate in this composition
# PHP-FPM & nginx Web Server
services:
  # PHP 7.2 FPM Image Container
  php-7-2-fpm:
    container_name: php-7-2-fpm
    tty: true
    restart: unless-stopped
    build: 
      context: .
      target: php-7-2-build
      dockerfile: php-7-2-fpm.Dockerfile
      args:
        - NPM_VERSION=${NPM_VERSION}
        - APP_ENV=${APP_ENV}
      labels:
        ewc.name: "Web App"
        ewc.description: "PHP-FPM Web App"
        ewc.php.version: "7.2"
    image: $BUILD_IMAGE:$BUILD_IMAGE_TAG
    environment:
        - NPM_VERSION=${NPM_VERSION}
    working_dir: /var/www
    volumes:
      - ./public_html:/var/www/public
      - ./docker-files/php/local.ini:/usr/local/etc/php.ini
    networks:
      - webapp_network

  # Nginx Webserver Image Container
  nginx-web-server:
    container_name: nginx-web-server
    tty: true
    restart: unless-stopped
    image: nginx:1.19-alpine 
    ports:
      - ${APP_PORT}:80
      - ${APP_SSL_PORT}:443
    volumes:
      - ./public_html:/var/www/public
      - ./docker-files/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - webapp_network

# Custom network for composed containers to communicate on
networks:
  webapp_network:
    driver: bridge
